# Generated by Django 4.1.3 on 2022-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('height', models.FloatField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('ageNow', models.IntegerField(null=True)),
                ('alldressing', models.TextField(null=True)),
                ('occrAdd', models.TextField(null=True)),
                ('occrDate', models.DateField(null=True)),
                ('writngTarget', models.TextField(null=True)),
            ],
        ),
    ]
