# Generated by Django 4.1.3 on 2022-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('height', models.FloatField()),
                ('age', models.IntegerField()),
                ('ageNow', models.IntegerField()),
                ('alldressing', models.TextField()),
                ('occrAdd', models.TextField()),
                ('writngTarget', models.TextField()),
            ],
        ),
    ]
